import bcrypt from 'bcryptjs';


const data = {
    users: [
        {
          name: 'Souheil',
          email: 'khalfallah.souheil@gmail.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: true,
        },
        {
          name: 'Iyadh',
          email: 'user@example.com',
          password: bcrypt.hashSync('1234', 8),
          isAdmin: false,
        },
      ],
    products: [
        {
            _id:'1',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'adidas',
            rating: 5,
            numReviews: 10,
            description: 'good product',
            countInStock: 0,
        },
        {
            _id:'2',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-2.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'good product',
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-3.jpg',
            price: 65,
            brand: 'Nike',
            rating: 3.4,
            numReviews: 10,
            description: 'good product',
            countInStock: 0,
        },
        {
            _id:'4',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-1.jpg',
            price: 68,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 12,
            description: 'good product',
            countInStock: 10,
        },
        {
            _id:'5',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-5.jpg',
            price: 56,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            description: 'good product',
            countInStock: 16,
        },
        {
            _id:'6',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-6.jpg',
            price: 76,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            description: 'good product',
            countInStock: 6,
        },
    ],
};

export default data;