const data = {
    products: [
        {
            _id:'1',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-1.jpg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-2.jpg',
            price: 50,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-3.jpg',
            price: 65,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-1.jpg',
            price: 68,
            brand: 'Nike',
            rating: 4,
            numReviews: 12,
            countInStock: 10,
        },
        {
            _id:'5',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-5.jpg',
            price: 56,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 16,
        },
        {
            _id:'6',
            name: 'Full Zip Running Shirts',
            category: 'shirts',
            image: '/images/product-6.jpg',
            price: 76,
            brand: 'Nike',
            rating: 5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};

export default data;